
FROM python:3.11-slim

WORKDIR /app

RUN pip install --no-cache-dir flask gunicorn

ONBUILD COPY . .

ONBUILD RUN pip install -r requirements.txt

EXPOSE 5000

CMD ["gunicorn", "--bind", "0.0.0.0:5000", "wsgi:app"]

