
services:
  backend:
    build: ./backend
    networks:
      - app-network

  nginx:
    build: ./nginx-image
    ports:
      - "8080:80"
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
