
services:
  api:
    build: .

    ports:
     - "${API_PORT}:${API_PORT}"
    networks:
      - api-network
    environment:
      - REDIS_HOST:${REDIS_HOST}
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis:7-alpine
    volumes:
      - redis-data:/data
    networks:
      - api-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-admin:
    image: rediscommander/redis-commander:latest

    environment:
      - REDIS_HOSTS=redis
    ports:
      - "8001:8001"
    networks:
      - api-network
    profiles:
      - "dev"

volumes:
   redis-data:

networks:
  api-network:


